<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="cpj" name="com.yiibai.primera.testng.cases.LoginTest" tests="5" failures="3" timestamp="26 Sep 2017 07:42:09 GMT" time="206.359" errors="1">
  <testcase name="loginConfim" time="34.755" classname="com.yiibai.primera.testng.cases.LoginTest"/>
  <testcase name="loginErrorUser" time="45.886" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginErrorUser(
报错类:LoginTest
报错行号:31)
	at com.yiibai.primera.testng.cases.LoginTest.loginErrorUser(LoginTest.java:31)
]]>
    </failure>
  </testcase> <!-- loginErrorUser -->
  <testcase name="loginChinese" time="40.449" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginChinese(
报错类:LoginTest
报错行号:52)
	at com.yiibai.primera.testng.cases.LoginTest.loginChinese(LoginTest.java:52)
]]>
    </failure>
  </testcase> <!-- loginChinese -->
  <testcase name="loginConfim2" time="46.992" classname="com.yiibai.primera.testng.cases.LoginTest">
    <error type="java.lang.AssertionError" message="帐号密码对的情况登录 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 帐号密码对的情况登录 expected [true] but found [false]
	at 
报错信息: expected [true] but found [false].
报错方法名:loginConfim2(
报错类:LoginTest
报错行号:83)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim2(LoginTest.java:83)
	at com.yiibai.primera.testng.cases.LoginTest.loginConfim2(LoginTest.java:84)
]]>
    </error>
  </testcase> <!-- loginConfim2 -->
  <testcase name="loginErrorNum" time="38.277" classname="com.yiibai.primera.testng.cases.LoginTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at 
报错信息: expected [true] but found [false].
报错方法名:loginErrorNum(
报错类:LoginTest
报错行号:41)
	at com.yiibai.primera.testng.cases.LoginTest.loginErrorNum(LoginTest.java:41)
]]>
    </failure>
  </testcase> <!-- loginErrorNum -->
</testsuite> <!-- com.yiibai.primera.testng.cases.LoginTest -->
